version: "3.8"

services:
  meny-api:
    container_name: meny-api
    image: meny-api
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    depends_on:
      - meny-db
    env_file: ./apps/api/env/docker-compose.env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - 9001:3000
    volumes:
      - ./src:/opt/meny/src
      - ./test:/opt/meny/test

  meny-db:
    container_name: meny-db
    image: postgres:15.2-alpine
    restart: always
    env_file: ./apps/api/env/postgres.env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local