version: "3.8"

services:
  meny-dev:
    container_name: meny-dev
    image: meny-dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    depends_on:
      - meny-db
    env_file: env/development.env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - 9001:3000
    volumes:
      - ./src:/opt/meny/src
      - ./test:/opt/meny/test

  meny-db:
    container_name: meny-db
    image: postgres:15.2-alpine
    restart: always
    env_file: env/postgres.env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local